apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: open-services
spec:
  releaseName: kong
  chart:
    spec:
      chart: kong
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
# Default values
  values:
    ingressController:
      enabled: true
      installCRDs: false
    postgresql:
      enabled: false
    env:
      database: "off"